################################
######     User Login     ######    
################################
POST http://localhost:3000/user-login
Content-Type: application/json

{
    "Username": "abu",
    "Password": "123"
}

###################################
######     User Register     ######    
###################################
POST http://localhost:3000/register-user
Content-Type: application/json

{
    "Username": "abu",
    "Password": "123",
    "name": "aahh",
    "email": "aahh@gmail.com"
}

####################################
######     Admin Register     ######    
####################################
POST http://localhost:3000/register-admin
Content-Type: application/json

{
    "Username": "admin",
    "Password": "admin123",
    "name": "Admin User",
    "email": "admin@example.com"
}

#################################
######     Admin Login     ######    
#################################
POST http://localhost:3000/login-admin
Content-Type: application/json

{
    "Username": "admin",
    "Password": "admin123"
}

##################################
######     Create Rental     ######    
##################################
POST http://localhost:3000/create-rental
Content-Type: application/json

{
  "rentalName": "jat",
  "gender": "Male",
  "customerId": "01",
  "rentalDate": "2023-01-01",
  "phoneNo": "01234567890",
  "carType": "lambo"
}

##################################
######     Update Visit     ######    
##################################
PATCH http://localhost:3000/update-visit/5ffac8e3f7c1890c4af33929
Content-Type: application/json

{
  "rentalName": "John Doe",
    "gender": "Male",
    "phoneNo": "USA",
    "carType": "123 Main St",
    "customerId": "123-456-7890",
    "rentalDate": "ABC123",
}

#######################################
######     Delete Rental     ######    
#######################################
DELETE http://localhost:3000/delete-rental/jat
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDQ1MzI3OTUsImV4cCI6MTcwNDUzNjM5NX0.SUi5swAB8l7QT6_vU7lmUVnmIYyiAnHbVqThcMPw9Lo



#######################################
######     Get Visit Details     ######    
#######################################
GET http://localhost:3000/visit-details
Content-Type: application/json

#######################################
POST http://localhost:3000/register-security
Content-Type: application/json

{
    "name": "John Doe",
    "id": "SG001",
    "workshift": "Day",
    "duration": "08:00",
    "date": "23-06-23"
}

####################
POST http://localhost:3000/login-security
Content-Type: application/json

{
    "id": "SG001",
    "name": "John Doe"
}
